### ISSUE TITLE
Can't build immugw on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by vmdave9** [codenotary/immugw#11]
I* can't build immugw on openSUSE Tumbleweed.

**What happened**
I get the following message when I do a "make all"
go: finding github.com/golang/protobuf v1.4.0-rc.4.0.20200313231945-b860323f09d0
go: error loading module requirements
make: *** [Makefile:50: immugw] Error 1

**What you expected to happen**
make to complete successfully.

**How to reproduce it (as minimally and precisely as possible)**
do a 
    git clone https://github.com/codenotary/immugw.git
then
   cd immugw
   make all

**Environment**
NAME="openSUSE Tumbleweed"
# VERSION="20210629"
ID="opensuse-tumbleweed"
go version
go version go1.11.13 linux/amd64

Complete make console log:
dave@dave-ThinkPad-T480:~/immudb-demo/immugw$ make all
go build -v -ldflags '-X "github.com/codenotary/immudb/cmd/version.Version=0.9.2-RC1" -X "github.com/codenotary/immudb/cmd/version.Commit=005a0c3456bb05ac9c2ff1ae48c709554e2a2673" -X "github.com/codenotary/immudb/cmd/version.BuiltBy=vmdave9@gmail.com" -X "github.com/codenotary/immudb/cmd/version.BuiltAt=1629044557"' ./cmd/immugw
go: finding github.com/codenotary/immudb v0.9.3-0.20210422101551-cdf372b3ecf6
go: finding github.com/prometheus/common v0.4.0
go: finding github.com/google/go-cmp v0.2.0
Fetching https://google.golang.org/protobuf?go-get=1
Fetching https://golang.org/x/sync?go-get=1
Fetching https://google.golang.org/grpc?go-get=1
go: finding github.com/stretchr/testify v1.5.1
go: finding github.com/jtolds/gls v4.20.0+incompatible
go: finding github.com/gopherjs/gopherjs v0.0.0-20181017120253-0766667cb4d1
go: finding github.com/prometheus/tsdb v0.7.1
Parsing meta tags from https://golang.org/x/sync?go-get=1 (status code 200)
get "golang.org/x/sync": found meta tag get.metaImport{Prefix:"golang.org/x/sync", VCS:"git", RepoRoot:"https://go.googlesource.com/sync"} at https://golang.org/x/sync?go-get=1
go: finding golang.org/x/sync v0.0.0-20181108010431-42b317875d0f
go: finding github.com/prometheus/procfs v0.0.0-20190507164030-5867b95ac084
Parsing meta tags from https://google.golang.org/grpc?go-get=1 (status code 200)
get "google.golang.org/grpc": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc?go-get=1
go: finding google.golang.org/grpc v1.25.1
Parsing meta tags from https://google.golang.org/protobuf?go-get=1 (status code 200)
get "google.golang.org/protobuf": found meta tag get.metaImport{Prefix:"google.golang.org/protobuf", VCS:"git", RepoRoot:"https://go.googlesource.com/protobuf"} at https://google.golang.org/protobuf?go-get=1
go: finding google.golang.org/protobuf v1.23.0
go: finding github.com/golang/protobuf v1.4.0
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
get "golang.org/x/tools": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools?go-get=1
go: finding golang.org/x/tools v0.0.0-20190328211700-ab21143f2384
go: finding github.com/envoyproxy/go-control-plane v0.9.0
go: finding google.golang.org/protobuf v1.22.0
Fetching https://golang.org/x/net?go-get=1
go: finding github.com/census-instrumentation/opencensus-proto v0.2.1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
get "golang.org/x/net": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net?go-get=1
go: finding golang.org/x/net v0.0.0-20180724234803-3673e40ba225
go: finding github.com/smartystreets/assertions v0.0.0-20180927180507-b2de0cb4f26d
go: finding github.com/kr/text v0.1.0
go: finding google.golang.org/protobuf v1.23.1-0.20200526195155-81db48ad09cc
go: finding google.golang.org/protobuf v1.21.0
go: finding github.com/kr/pty v1.1.1
go: finding github.com/coreos/etcd v3.3.10+incompatible
go: finding github.com/shurcooL/sanitized_anchor_name v1.0.0
go: finding github.com/prometheus/client_model v0.0.0-20190812154241-14fe0d1b01d4
go: finding github.com/envoyproxy/protoc-gen-validate v0.1.0
go: github.com/codenotary/immudb@v0.9.3-0.20210422101551-cdf372b3ecf6: unknown revision cdf372b3ecf6
go: finding github.com/magiconair/properties v1.8.0
go: finding github.com/ugorji/go v1.1.4
go: finding github.com/envoyproxy/go-control-plane v0.9.1-0.20191026205805-5f8ba28d4473
go: finding github.com/russross/blackfriday/v2 v2.0.1
go: finding google.golang.org/grpc v1.23.0
go: finding github.com/golang/protobuf v1.4.0-rc.4.0.20200313231945-b860323f09d0
go: error loading module requirements
make: *** [Makefile:50: immugw] Error 1

**Comment by mmeloni** [comment]
Hi @vmdave9 , could you try to upgrade GO to 1.13 version? GO 11 provides only a partial support to modules.
Ty

**Comment by vmdave9** [comment]
Thank you very much for your prompt response, TY. I will try that
straight-away now. Stay tuned.
DJ

**Comment by mmeloni** [comment]
Ok, let us know. Ty

**Comment by vmdave9** [comment]
Yup, that worked. You can now close the issue.
Build successful, now you can launch immugw.
***@***.***:~/immudb-demo/immugw
$ go version
go version go1.16.7 linux/amd64

Might want to update the doc to mention this nit.
DJ

**Comment by mmeloni** [comment]
Ok, ty
